version: '3.2'
services:
  llum-app:
    build:
      context: .
    image: llum-app
    environment:
      - TYPEORM_CONNECTION=mysql
      - TYPEORM_SYNCHRONIZE=true
      - TYPEORM_ENTITIES=dist/entities/*.js
      - TYPEORM_HOST=
      - TYPEORM_PORT=
      - TYPEORM_USERNAME=
      - TYPEORM_PASSWORD=
      - TYPEORM_DATABASE=
    ports:
      - '3000:3000'
    container_name: llum-app
